
package demo.ax.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Dcm", targetNamespace = "http://wsdl.intf.dcm.intel.com/", wsdlLocation = "http://localhost:8688/DCMWsdl/dcm.wsdl")
public class Dcm_Service
    extends Service
{

    private final static URL DCM_WSDL_LOCATION;
    private final static WebServiceException DCM_EXCEPTION;
    private final static QName DCM_QNAME = new QName("http://wsdl.intf.dcm.intel.com/", "Dcm");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8688/DCMWsdl/dcm.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DCM_WSDL_LOCATION = url;
        DCM_EXCEPTION = e;
    }

    public Dcm_Service() {
        super(__getWsdlLocation(), DCM_QNAME);
    }

    public Dcm_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DCM_QNAME, features);
    }

    public Dcm_Service(URL wsdlLocation) {
        super(wsdlLocation, DCM_QNAME);
    }

    public Dcm_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DCM_QNAME, features);
    }

    public Dcm_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Dcm_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Dcm
     */
    @WebEndpoint(name = "DcmPort")
    public Dcm getDcmPort() {
        return super.getPort(new QName("http://wsdl.intf.dcm.intel.com/", "DcmPort"), Dcm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dcm
     */
    @WebEndpoint(name = "DcmPort")
    public Dcm getDcmPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://wsdl.intf.dcm.intel.com/", "DcmPort"), Dcm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DCM_EXCEPTION!= null) {
            throw DCM_EXCEPTION;
        }
        return DCM_WSDL_LOCATION;
    }

}
